name: Generate M3U

on:
  schedule:
    - cron: '*/30 * * * *'   # Runs every 30 minutes
  workflow_dispatch:          # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pyperclip

      - name: Install Playwright browsers
        run: |
          playwright install

      - name: Run M3U generator
        run: python generate_m3u.py

      - name: Commit and push to gh-pages
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -B gh-pages
          git add index.m3u
          git commit -m "Update M3U"
          git push -f origin gh-pages
